// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqdmesndmfphlevakgqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZG1lc25kbWZwaGxldmFrZ3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzkwNTksImV4cCI6MjA2OTE1NTA1OX0.T_P1jKxpXp0RPZeJJN4vzJEwDPdqM9WvIQTELbz2Ato";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});